# Generated by Django 4.2.11 on 2025-03-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='song_name',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.AddField(
            model_name='note',
            name='artist',
            field=models.TextField(default='artist1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='length',
            field=models.TextField(default='length1'),
            preserve_default=False,
        ),
    ]
