# Generated by Django 4.2.11 on 2025-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_content_note_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='album_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
