# Generated by Django 5.1.7 on 2025-03-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='song_name',
            field=models.CharField(max_length=300),
        ),
    ]
